apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-rabbitmq-repo
spec:
  fetch:
    imgpkgBundle:
      image: harbor.h2o-2-10553.h2o.vmware.com/rabbitmq/tanzu-rabbitmq-package-repo:1.2.0
